name: Deploy Python Server to Azure VM with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/python-server:latest .
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/python-server:latest
    
    - name: Deploy Docker container on Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_PASSWORD }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/python-server:latest
          docker stop python-server || true
          docker rm python-server || true
          docker run -d --name python-server -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/python-server:latest
